pokeapi:
  url: https://pokeapi.co/api/v2/pokemon
  img-artwork-url: https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/%d.png
  navigation-url: http://localhost:8081/api/v1/pokemon?limit=%s&offset=%d

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pokemon_api_v0
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

jwt:
  expirationTimeMins: 5